--- 
javascripts: 
- base: 
  - jquery
  - soundmanager2-nodebug-jsmin
  - rails
  - application
  - enhance
  - excanvas
  - jquery-ui-1.8.9.custom.min
  - jquery.formalize
  - jquery.inline_label.min
  - visualize.jQuery
  - jquery.fancybox-1.3.4.pack
  - jquery.elastic
stylesheets: 
- base: 
  - blueprint/reset
  - ui-pomodoro_crate/jquery-ui-1.8.9.custom
  - web_fonts
  - screen
  - visualize
  - visualize-light
  - jquery.fancybox-1.3.4