--- 
javascripts: 
- base: 
  - jquery
  - rails
  - application
  - enhance
  - excanvas
  - jquery-ui-1.8.9.custom.min
  - jquery.inline_label.min
  - visualize.jQuery
  - jquery.fancybox-1.3.4.pack
  - jquery.elastic.source
  - event_calendar
  - jquery.quickClear
  - ajaxify
  - jquery.cookie
- static:
  - jquery-1.6.1.min
  - jquery.fancybox-1.3.4.pack
  - jquery.easing-1.3.pack
  - static
  - jquery.elastic.source
- modal:
  - jquery-1.6.1.min
  - rails
  - application
  - soundmanager2-nodebug-jsmin
stylesheets: 
- base: 
  - blueprint/reset
  - web_fonts
  - screen
  - visualize
  - visualize-light
  - jquery.fancybox-1.3.4
  - event_calendar
  - ui-pomodoro_crate/jquery-ui-1.8.9.custom
- static:
  - blueprint/reset
  - jquery.fancybox-1.3.4
  - web_fonts
  - styles
- modal:
  - blueprint/reset
  - web_fonts
  - screen
  - login